// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ops.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindItemRequest) Reset() {
	*x = FindItemRequest{}
	mi := &file_ops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindItemRequest) ProtoMessage() {}

func (x *FindItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindItemRequest.ProtoReflect.Descriptor instead.
func (*FindItemRequest) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{0}
}

func (x *FindItemRequest) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *FindItemRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ColumnMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnMeta) Reset() {
	*x = ColumnMeta{}
	mi := &file_ops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnMeta) ProtoMessage() {}

func (x *ColumnMeta) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnMeta.ProtoReflect.Descriptor instead.
func (*ColumnMeta) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{1}
}

func (x *ColumnMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ColumnMeta) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ColumnMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Meta          *ColumnMeta            `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_ops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{2}
}

func (x *Column) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Column) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Column) GetMeta() *ColumnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type FindItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Columns       []*Column              `protobuf:"bytes,4,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindItemResponse) Reset() {
	*x = FindItemResponse{}
	mi := &file_ops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindItemResponse) ProtoMessage() {}

func (x *FindItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindItemResponse.ProtoReflect.Descriptor instead.
func (*FindItemResponse) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{3}
}

func (x *FindItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FindItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindItemResponse) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FindItemResponse) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         string                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_ops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{4}
}

func (x *CreateItemRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *CreateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateItemRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateItemRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateItemRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_ops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{5}
}

func (x *CreateItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_ops_proto protoreflect.FileDescriptor

const file_ops_proto_rawDesc = "" +
	"\n" +
	"\tops.proto\x12\tops.proto\"?\n" +
	"\x0fFindItemRequest\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"F\n" +
	"\n" +
	"ColumnMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"Y\n" +
	"\x06Column\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12)\n" +
	"\x04meta\x18\x03 \x01(\v2\x15.ops.proto.ColumnMetaR\x04meta\"y\n" +
	"\x10FindItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12+\n" +
	"\acolumns\x18\x04 \x03(\v2\x11.ops.proto.ColumnR\acolumns\"\x7f\n" +
	"\x11CreateItemRequest\x12\x14\n" +
	"\x05board\x18\x01 \x01(\tR\x05board\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\"$\n" +
	"\x12CreateItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xa1\x01\n" +
	"\rMondayService\x12E\n" +
	"\bFindItem\x12\x1a.ops.proto.FindItemRequest\x1a\x1b.ops.proto.FindItemResponse0\x01\x12I\n" +
	"\n" +
	"CreateItem\x12\x1c.ops.proto.CreateItemRequest\x1a\x1d.ops.proto.CreateItemResponseB3Z1github.com/CatalinCaprita/SPO/slack-bot/ops/protob\x06proto3"

var (
	file_ops_proto_rawDescOnce sync.Once
	file_ops_proto_rawDescData []byte
)

func file_ops_proto_rawDescGZIP() []byte {
	file_ops_proto_rawDescOnce.Do(func() {
		file_ops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ops_proto_rawDesc), len(file_ops_proto_rawDesc)))
	})
	return file_ops_proto_rawDescData
}

var file_ops_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ops_proto_goTypes = []any{
	(*FindItemRequest)(nil),    // 0: ops.proto.FindItemRequest
	(*ColumnMeta)(nil),         // 1: ops.proto.ColumnMeta
	(*Column)(nil),             // 2: ops.proto.Column
	(*FindItemResponse)(nil),   // 3: ops.proto.FindItemResponse
	(*CreateItemRequest)(nil),  // 4: ops.proto.CreateItemRequest
	(*CreateItemResponse)(nil), // 5: ops.proto.CreateItemResponse
}
var file_ops_proto_depIdxs = []int32{
	1, // 0: ops.proto.Column.meta:type_name -> ops.proto.ColumnMeta
	2, // 1: ops.proto.FindItemResponse.columns:type_name -> ops.proto.Column
	0, // 2: ops.proto.MondayService.FindItem:input_type -> ops.proto.FindItemRequest
	4, // 3: ops.proto.MondayService.CreateItem:input_type -> ops.proto.CreateItemRequest
	3, // 4: ops.proto.MondayService.FindItem:output_type -> ops.proto.FindItemResponse
	5, // 5: ops.proto.MondayService.CreateItem:output_type -> ops.proto.CreateItemResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ops_proto_init() }
func file_ops_proto_init() {
	if File_ops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ops_proto_rawDesc), len(file_ops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ops_proto_goTypes,
		DependencyIndexes: file_ops_proto_depIdxs,
		MessageInfos:      file_ops_proto_msgTypes,
	}.Build()
	File_ops_proto = out.File
	file_ops_proto_goTypes = nil
	file_ops_proto_depIdxs = nil
}
