// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ops.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MondayService_FindItem_FullMethodName   = "/ops.proto.MondayService/FindItem"
	MondayService_CreateItem_FullMethodName = "/ops.proto.MondayService/CreateItem"
)

// MondayServiceClient is the client API for MondayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MondayServiceClient interface {
	FindItem(ctx context.Context, in *FindItemRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FindItemResponse], error)
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error)
}

type mondayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMondayServiceClient(cc grpc.ClientConnInterface) MondayServiceClient {
	return &mondayServiceClient{cc}
}

func (c *mondayServiceClient) FindItem(ctx context.Context, in *FindItemRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FindItemResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MondayService_ServiceDesc.Streams[0], MondayService_FindItem_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FindItemRequest, FindItemResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MondayService_FindItemClient = grpc.ServerStreamingClient[FindItemResponse]

func (c *mondayServiceClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateItemResponse)
	err := c.cc.Invoke(ctx, MondayService_CreateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MondayServiceServer is the server API for MondayService service.
// All implementations must embed UnimplementedMondayServiceServer
// for forward compatibility.
type MondayServiceServer interface {
	FindItem(*FindItemRequest, grpc.ServerStreamingServer[FindItemResponse]) error
	CreateItem(context.Context, *CreateItemRequest) (*CreateItemResponse, error)
	mustEmbedUnimplementedMondayServiceServer()
}

// UnimplementedMondayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMondayServiceServer struct{}

func (UnimplementedMondayServiceServer) FindItem(*FindItemRequest, grpc.ServerStreamingServer[FindItemResponse]) error {
	return status.Error(codes.Unimplemented, "method FindItem not implemented")
}
func (UnimplementedMondayServiceServer) CreateItem(context.Context, *CreateItemRequest) (*CreateItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedMondayServiceServer) mustEmbedUnimplementedMondayServiceServer() {}
func (UnimplementedMondayServiceServer) testEmbeddedByValue()                       {}

// UnsafeMondayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MondayServiceServer will
// result in compilation errors.
type UnsafeMondayServiceServer interface {
	mustEmbedUnimplementedMondayServiceServer()
}

func RegisterMondayServiceServer(s grpc.ServiceRegistrar, srv MondayServiceServer) {
	// If the following call panics, it indicates UnimplementedMondayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MondayService_ServiceDesc, srv)
}

func _MondayService_FindItem_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FindItemRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MondayServiceServer).FindItem(m, &grpc.GenericServerStream[FindItemRequest, FindItemResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MondayService_FindItemServer = grpc.ServerStreamingServer[FindItemResponse]

func _MondayService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MondayServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MondayService_CreateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MondayServiceServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MondayService_ServiceDesc is the grpc.ServiceDesc for MondayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MondayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ops.proto.MondayService",
	HandlerType: (*MondayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItem",
			Handler:    _MondayService_CreateItem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindItem",
			Handler:       _MondayService_FindItem_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ops.proto",
}
